### ISSUE TITLE
Manual mapping a NativeAOT binary causes Access Violation

### ISSUE THREAD

**Issue by slxdy** [jdewera/lunar#2]
For some time, I've been trying to manually map a DLL generated by NativeAOT. No matter which injector/script (including some I wrote myself) I use, it always ends up throwing an Access Violation. Can you help me look into that?

**Comment by h3xds1nz** [comment]
@slxdy I've fixed page protection in #1, however do note that for NativeAOT it requires one additional step, that is either before running main you manually add a loader reference or hook `GetModuleHandleExW` (WinAPI) / `PalGetModuleHandleFromPointer` in the library itself to return the base address, otherwise it won't work.

**Comment by slxdy** [comment]
Ah perfect, I see. Thanks!
